# -*- coding: utf-8 -*-
"""Clase_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jGAP1vjbeEUv1eS1mV6UECgOg0Mt7sgg

La idea es que ustedes vayan resolviendo los ejercicios sin la necesidad de instalarse nada en sus computadoras. 
Antes que nada, creen una copia de este archivo en su ***Google Drive*** para tener permisos de edición, luego pueden compartirlo con quien quieran, tengan cuidado con los permisos al momento de compartir!!!!!!!. Si quieren, nos pueden compartir su documento a los docentes para que hagamos las correcciones y ayudemos con las dudas.

### Agustin: **agustin.otero@estudiantes.unahur.edu.ar** ###


En los bloques de código como el que les aparece aca abajo, se puede programar en Python, al pararse dentro del bloque, aparecerá un ícono de "*play*" en la esquina superior izquierda, "*clickeando*" en este ícono, se ejecuta el código escrito y se muestra la salida debajo, probemos:
"""

print("Hello world")

"""El comando **print** nos va a imprimir por pantalla lo que tenga dentro de su parentesis.

Ahora haganlo ustedes, pero imprimiendo **hola mundo**
"""

print("Hola perris")

"""Acuerdensen de poner las comillas (") sino no toma lo escrito, lo toma como una variable.

Tambien pueden imprimir numeros o caracteres especiales.

prueben imprimiendo un numero cualquiera, como por ejemplo un numero de telefono o un mail.
"""

print("mi nombre es alejandro , mi numero de afiliado es 485.256 y mi mail es alejandro@yahoo.com.ar")

# pruebenlo ustedes.
print("I´m IronMan")

"""¿Ven algo raro en el codigo anterior?

El **#** se utiliza para hacer **comentarios** en una sola linea.

Los comentarios son inscrustaciones en el codigo de anotaciones legibles para ayudar al programador a comprender o **documentar** el codigo.

En Python para comentar **solo una linea** se utiliza el (#). En caso de que se quiera comentar mas de una linea, se utiliza la triple comilla (') al **principio del comentario y al final**.
"""

print("esta mañana es hermosa")
#print("Se puso a llover")
'''
print("esta muy ventoso hoy")
print("se vino santa rosa")
'''
print("esta para darle una vuelta al perro")
print("hoy no salis firulays")

"""Juguemos con los comentarios para cambiar el clima y salir a pasear o no.

Vamos a conocer las variables.

las variables son "cajas" en las cuales vamos a guardar nuestros datos. cada variable tiene su nombre propio e irrepetible.

Creen la variable cualidad para describir con un breve texto la banda mencionada e imprimanlo en pantalla.
"""

banda = "Miranda"
cualidad = "perfecta"

print(banda)
print ()

"""Las variables no son inmutables, se pueden modificar como veremos a continuacion.

Asique cuidado al momento de modificarlas.
"""

numero = 1

print(numero)
print(numero)

numero = "jaja, te lo cambie"

print(numero)

número = 79

print(numero)

"""Una variable no solo contiene informacion que le pongaos nosotros, sino tambien informacion procesada por nuestro algoritmo."""

num1 = 3
num2 = 5
suma = num1 + num2

print(num1)
print(num2)
print(suma)

"""¿que pasa si queremos imprimir varias variables en una sola linea?

Para ayudarnos tenemos a nuestro amigo el mas (+) que a parte de hacer la operacion de suma con variables numericas, concatena cuando se trata de imprimir cadenas de caracteres (string). Tambien se puede concatenar con la coma(,).

Hay que tener en cuenta que las variable creadas mas arriba en el documento tambien sirven para utilizarlas despues. En este ejemplo vamos a traer la variable "banda" y "cualidad" formando una sola frase.
"""

print("la banda", banda + " es " + cualidad)

"""Estuvimos hablando de cariables numericas y varibles de cadenas de caracteres, ¿que son?

Estos son **tipos de datos**, son los tipos de datos que acepta la computadora para procesar.

Dentro de los tipos de datos numericos existen varios tipos, pero por el momento solo utilizaremos los **enteros**

Los tipos de datos conocidos hasta ahora son :

*   **string** (cadena de caracteres)
*   **int** (enteros)
"""

numero1 = "1"
numero2 = "2"
print("Concatenación:", numero1 + numero2) #Suma caracteres (strings), no números
print("Suma:", int(numero1) + int(numero2)) #Suma números enteros